Add deployment health validation

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -6,13 +6,10 @@ on:
       - main
 
 jobs:
-
   build:
-
     runs-on: ubuntu-latest
 
     steps:
-
       - uses: actions/checkout@v4
 
       - uses: docker/login-action@v3
@@ -30,15 +27,11 @@ jobs:
             alokkumar01/production-cicd-pipeline:latest
 
   deploy:
-
     needs: build
-
     runs-on: ubuntu-latest
 
     steps:
-
       - name: Deploy to EC2
-
         uses: appleboy/ssh-action@v1.0.3
 
         with:
@@ -50,7 +43,6 @@ jobs:
             docker pull alokkumar01/production-cicd-pipeline:latest
 
             docker stop app-container || true
-
             docker rm app-container || true
 
             docker run -d \
@@ -59,3 +51,21 @@ jobs:
               -e NODE_ENV=production \
               --restart unless-stopped \
               alokkumar01/production-cicd-pipeline:latest
+
+            echo "Waiting for container startup..."
+            sleep 15
+
+            STATUS=$(docker inspect \
+              --format='{{.State.Health.Status}}' \
+              app-container)
+
+            echo "Container Status: $STATUS"
+
+            if [ "$STATUS" != "healthy" ]; then
+              echo "Deployment Failed"
+              exit 1
+            fi
+
+            echo "Deployment Successful"
+
+            docker image prune -af
